import { Montserrat } from 'next/font/google'
import './globals.css'
import { ConfigProvider } from 'antd'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Repair Café',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <ConfigProvider
        theme={{
          token: {
            fontFamily: montserrat.style.fontFamily,
          }
        }}>
        <body className={montserrat.className}>
          {children}
        </body>
      </ConfigProvider>
    </html >
  )
}
