import { Montserrat } from 'next/font/google'
import { error } from 'console';

import {MantineProvider, ColorSchemeScript, createTheme} from '@mantine/core';

import './globals.css'
import '@mantine/core/styles.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Repair Café',
  description: 'Generated by create next app',
}

const theme = createTheme({
  colors: {
    purple: [
      "#F5F5FB",
      "#DBDBEB",
      "#E3E6FF",
      "#939AFE",
      "#5D6BFF",
      "#5060FF"
    ],
    white: [
      "#2E2F34",
      "#4B4C57",
      "#A9ABC2",
      "#F5F5F5",
      "#FFFFFF"
    ],
    states: [
      "#FF3838",
      "#93D724"
  ]}
});

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head><ColorSchemeScript /></head>
      <body className={montserrat.className}>
        <MantineProvider theme={theme} defaultColorScheme="light">
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
