import { Montserrat } from 'next/font/google'
import {MantineProvider, ColorSchemeScript, createTheme} from '@mantine/core';

import global from './globals.css'
import '@mantine/core/styles.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Repair Café',
  description: 'Generated by create next app',
}

const theme = createTheme({
  
  fontFamily: 'Montserrat, sans-serif',

  colors: {
    primaryColor: [
      "#D9DDFE",
      "#BEC4FE",
      "#A2ABFE",
      "#8792FF",
      "#6B79FF",
      "#5060FF",
      "#3E4CCC",
      "#2D3899",
      "#1B2566",
      "#0A1133"
    ],
    secondaryColor: [
      "#2E2F34",
      "#4B4C57",
      "#717280",
      "#9193A5",
      "#A9ABC2",
      "#BDBDD1",
      "#CFCFDE",
      "#DBDBEB",
      "#F5F5FB",
      "#FFFFFF"
    ],
    terciaryColor: [
      "#840000",
      "#960000",
      "#B20000",
      "#CC1717",
      "#DF1F1F",
      "#EB2D2D",
      "#FF3838",
      "#FF5F5F",
      "#FF8787",
      "#FFB8B8"
    ],
    purple: [
      "#F5F5FB",
      "#DBDBEB",
      "#E3E6FF",
      "#939AFE",
      "#5D6BFF",
      "#5060FF"
    ],
    white: [
      "#FFFFFF",
      "#F5F5F5",
      "#A9ABC2",
      "#4B4C57",
      "#2E2F34",
    ],
    error: ["#FF3838"],
    sucess: ["#93D724"]
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head><ColorSchemeScript /></head>
      <body className={montserrat.className}>
        <MantineProvider theme={theme} defaultColorScheme="light">
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
